import { Geist, Geist_Mono } from "next/font/google";

import 'bootstrap/dist/css/bootstrap.min.css'; 
import 'bootstrap-icons/font/bootstrap-icons.css';
import Navigation from "./components/Navigation";
import Footer from "./components/Footer";
import Link from "next/link";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>


        <Navigation />
        {children}
       
       
        <Footer />
      </body>
    </html> 
  );
}

